In [2]:
import numpy as np
import pandas as pd
import datetime

data = pd.read_csv('CreditCardCustomers1.csv')
data

,CLIENTNUM,Attrition_Flag,DOB_Year,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Months_Inactive_12_mon,Credit_Limit,Total_Trans_Ct,Avg_Utilization_Ratio
0,768805383,Existing Customer,1976,M,3,High School,Married,$60K - $80K,Blue,39,1,12691.0,42,0.061
1,818770008,Existing Customer,1972,F,5,Graduate,Single,Less than $40K,Blue,44,1,8256.0,33,0.105
2,713982108,Existing Customer,1970,M,3,Graduate,Married,$80K - $120K,Blue,36,1,3418.0,20,0.000
3,769911858,Existing Customer,1981,F,4,High School,Unknown,Less than $40K,Blue,34,4,3313.0,20,0.760
4,709106358,Existing Customer,1981,M,3,Uneducated,Married,$60K - $80K,Blue,21,1,4716.0,28,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,1971,M,2,Graduate,Single,$40K - $60K,Blue,40,2,4003.0,117,0.462
10123,710638233,Attrited Customer,1980,M,2,Unknown,Divorced,$40K - $60K,Blue,25,2,4277.0,69,0.511
10124,716506083,Attrited Customer,1977,F,1,High School,Married,Less than $40K,Blue,36,3,5409.0,60,0.000
10125,717406983,Attrited Customer,1991,M,2,Graduate,Unknown,$40K - $60K,Blue,36,3,5281.0,62,0.000
10126,714337233,Attrited Customer,1978,F,2,Graduate,Married,Less than $40K,Silver,25,2,10388.0,61,0.189

In [3]:
print("Number of rows: ",data.shape[0],"\n")
date = datetime.date.today()
currentYear = date.year
custAge = currentYear - data["DOB_Year"]
data.insert(3,"Customer Age",custAge)
data

Number of rows:  10127

,CLIENTNUM,Attrition_Flag,DOB_Year,Customer Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Months_Inactive_12_mon,Credit_Limit,Total_Trans_Ct,Avg_Utilization_Ratio
0,768805383,Existing Customer,1976,48,M,3,High School,Married,$60K - $80K,Blue,39,1,12691.0,42,0.061
1,818770008,Existing Customer,1972,52,F,5,Graduate,Single,Less than $40K,Blue,44,1,8256.0,33,0.105
2,713982108,Existing Customer,1970,54,M,3,Graduate,Married,$80K - $120K,Blue,36,1,3418.0,20,0.000
3,769911858,Existing Customer,1981,43,F,4,High School,Unknown,Less than $40K,Blue,34,4,3313.0,20,0.760
4,709106358,Existing Customer,1981,43,M,3,Uneducated,Married,$60K - $80K,Blue,21,1,4716.0,28,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,1971,53,M,2,Graduate,Single,$40K - $60K,Blue,40,2,4003.0,117,0.462
10123,710638233,Attrited Customer,1980,44,M,2,Unknown,Divorced,$40K - $60K,Blue,25,2,4277.0,69,0.511
10124,716506083,Attrited Customer,1977,47,F,1,High School,Married,Less than $40K,Blue,36,3,5409.0,60,0.000
10125,717406983,Attrited Customer,1991,33,M,2,Graduate,Unknown,$40K - $60K,Blue,36,3,5281.0,62,0.000
10126,714337233,Attrited Customer,1978,46,F,2,Graduate,Married,Less than $40K,Silver,25,2,10388.0,61,0.189

In [4]:
print(data['Attrition_Flag'].unique(),"\n")
print(data["Education_Level"].unique(),"\n")
print(data['Card_Category'].unique(),"\n")

print(data['Card_Category'].value_counts(),"\n")

print("Number of Silver card Members:",data[data['Card_Category'] == 'Silver'].shape[0],"\n")
print("Number of Customers born after 1990:",data[data['DOB_Year'] > 1990].shape[0],"\n")
print("Number of Customers born between 1980 & 1985:",data[data['DOB_Year'].between(1980,1985)].shape[0],"\n")

print(data['Income_Category'].unique(),"\n")
print("Customers Income greater or equal to $60k and less or equal to $120k:", data[data['Income_Category'].isin(['$60K - $80K','$80K - $120K','$120K +'])].shape[0],"\n")

['Existing Customer' 'Attrited Customer']

['High School' 'Graduate' 'Uneducated' 'Unknown' 'College' 'Post-Graduate'
 'Doctorate']

['Blue' 'Gold' 'Silver' 'Platinum']

Card_Category
Blue        9436
Silver       555
Gold         116
Platinum      20
Name: count, dtype: int64

Number of Silver card Members: 555

Number of Customers born after 1990: 265

Number of Customers born between 1980 & 1985: 1857

['$60K - $80K' 'Less than $40K' '$80K - $120K' '$40K - $60K' '$120K +'
 'Unknown']

Customers Income greater or equal to $60k and less or equal to $120k: 3664

In [5]:
data.query('Card_Category == "Silver" & Income_Category == "Less than $40K" & Gender == "F"')

,CLIENTNUM,Attrition_Flag,DOB_Year,Customer Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Months_Inactive_12_mon,Credit_Limit,Total_Trans_Ct,Avg_Utilization_Ratio
129,710806083,Existing Customer,1971,53,F,1,Uneducated,Unknown,Less than $40K,Silver,36,2,11888.0,30,0.176
205,711441333,Existing Customer,1978,46,F,1,High School,Divorced,Less than $40K,Silver,35,2,10514.0,27,0.150
219,803043933,Existing Customer,1977,47,F,3,Uneducated,Divorced,Less than $40K,Silver,38,1,11127.0,25,0.165
227,711297483,Existing Customer,1974,50,F,2,Uneducated,Divorced,Less than $40K,Silver,34,4,13878.0,38,0.160
380,710865633,Existing Customer,1980,44,F,2,Graduate,Married,Less than $40K,Silver,33,2,12301.0,29,0.183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9960,717928308,Existing Customer,1981,43,F,1,Uneducated,Single,Less than $40K,Silver,34,2,13669.0,130,0.130
10032,712128258,Existing Customer,1972,52,F,4,High School,Single,Less than $40K,Silver,40,3,13704.0,116,0.155
10064,718614183,Attrited Customer,1978,46,F,4,High School,Unknown,Less than $40K,Silver,31,2,13651.0,71,0.000
10068,718655808,Existing Customer,1977,47,F,3,Uneducated,Married,Less than $40K,Silver,36,3,12944.0,105,0.093
10126,714337233,Attrited Customer,1978,46,F,2,Graduate,Married,Less than $40K,Silver,25,2,10388.0,61,0.189

In [6]:
df = data.query('DOB_Year > 1970 & Gender == "M" & Education_Level == "Graduate"')
df

,CLIENTNUM,Attrition_Flag,DOB_Year,Customer Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Months_Inactive_12_mon,Credit_Limit,Total_Trans_Ct,Avg_Utilization_Ratio
5,713061558,Existing Customer,1977,47,M,2,Graduate,Married,$40K - $60K,Blue,36,1,4010.0,24,0.311
9,719661558,Existing Customer,1973,51,M,2,Graduate,Single,$80K - $120K,Blue,36,3,11656.0,32,0.144
13,816082233,Existing Customer,1986,38,M,3,Graduate,Unknown,$60K - $80K,Blue,30,1,8547.0,33,0.195
32,709029408,Existing Customer,1980,44,M,4,Graduate,Married,$60K - $80K,Blue,36,1,8923.0,24,0.282
40,827111283,Existing Customer,1976,48,M,3,Graduate,Single,$80K - $120K,Blue,41,2,32426.0,28,0.018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10108,714471183,Attrited Customer,1974,50,M,4,Graduate,Divorced,$80K - $120K,Blue,39,3,17504.0,66,0.027
10111,710734308,Existing Customer,1972,52,M,1,Graduate,Single,$60K - $80K,Blue,40,3,6481.0,119,0.242
10114,720841533,Existing Customer,1992,32,M,0,Graduate,Married,Less than $40K,Blue,15,1,4700.0,96,0.000
10122,772366833,Existing Customer,1971,53,M,2,Graduate,Single,$40K - $60K,Blue,40,2,4003.0,117,0.462
10125,717406983,Attrited Customer,1991,33,M,2,Graduate,Unknown,$40K - $60K,Blue,36,3,5281.0,62,0.000

In [7]:
df.query('Dependent_count >= 3')

,CLIENTNUM,Attrition_Flag,DOB_Year,Customer Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Months_Inactive_12_mon,Credit_Limit,Total_Trans_Ct,Avg_Utilization_Ratio
13,816082233,Existing Customer,1986,38,M,3,Graduate,Unknown,$60K - $80K,Blue,30,1,8547.0,33,0.195
32,709029408,Existing Customer,1980,44,M,4,Graduate,Married,$60K - $80K,Blue,36,1,8923.0,24,0.282
40,827111283,Existing Customer,1976,48,M,3,Graduate,Single,$80K - $120K,Blue,41,2,32426.0,28,0.018
78,779058108,Existing Customer,1972,52,M,3,Graduate,Divorced,$60K - $80K,Blue,30,1,2536.0,23,0.719
80,715623483,Existing Customer,1974,50,M,3,Graduate,Married,$60K - $80K,Blue,37,4,8567.0,41,0.198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10058,715186608,Existing Customer,1978,46,M,4,Graduate,Married,$80K - $120K,Blue,35,2,3304.0,120,0.762
10076,712516608,Existing Customer,1978,46,M,3,Graduate,Married,$80K - $120K,Blue,36,2,3946.0,96,0.323
10079,715090008,Existing Customer,1976,48,M,4,Graduate,Single,$60K - $80K,Silver,36,3,28564.0,107,0.088
10087,713768358,Existing Customer,1976,48,M,4,Graduate,Single,$40K - $60K,Blue,35,2,7935.0,122,0.112
10108,714471183,Attrited Customer,1974,50,M,4,Graduate,Divorced,$80K - $120K,Blue,39,3,17504.0,66,0.027

In [8]:
df.query('Dependent_count >= 3 | (Months_Inactive_12_mon > 3 & Months_on_book > 36)')

,CLIENTNUM,Attrition_Flag,DOB_Year,Customer Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Months_Inactive_12_mon,Credit_Limit,Total_Trans_Ct,Avg_Utilization_Ratio
13,816082233,Existing Customer,1986,38,M,3,Graduate,Unknown,$60K - $80K,Blue,30,1,8547.0,33,0.195
32,709029408,Existing Customer,1980,44,M,4,Graduate,Married,$60K - $80K,Blue,36,1,8923.0,24,0.282
40,827111283,Existing Customer,1976,48,M,3,Graduate,Single,$80K - $120K,Blue,41,2,32426.0,28,0.018
78,779058108,Existing Customer,1972,52,M,3,Graduate,Divorced,$60K - $80K,Blue,30,1,2536.0,23,0.719
80,715623483,Existing Customer,1974,50,M,3,Graduate,Married,$60K - $80K,Blue,37,4,8567.0,41,0.198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10058,715186608,Existing Customer,1978,46,M,4,Graduate,Married,$80K - $120K,Blue,35,2,3304.0,120,0.762
10076,712516608,Existing Customer,1978,46,M,3,Graduate,Married,$80K - $120K,Blue,36,2,3946.0,96,0.323
10079,715090008,Existing Customer,1976,48,M,4,Graduate,Single,$60K - $80K,Silver,36,3,28564.0,107,0.088
10087,713768358,Existing Customer,1976,48,M,4,Graduate,Single,$40K - $60K,Blue,35,2,7935.0,122,0.112
10108,714471183,Attrited Customer,1974,50,M,4,Graduate,Divorced,$80K - $120K,Blue,39,3,17504.0,66,0.027